#!/usr/bin/env fish

alias b='build'
alias bp='build -p'
alias bd='build -d'
alias bdp='build -d -p'

# git
alias g="git"
alias gi="git init && git aa && git ci"

# ls
# TODO: pls, check lsd, pls
alias ls="lsd"
alias l="ls"
alias la="ls -A"
alias lA="ls -a"
alias ll="ls -lhA"
alias lsa="ls -A"
alias lsA="ls -a"

# open script
alias o="open"
alias oc="vim $HOME/.config/fish/config.fish"
alias og="vim $HOME/.gitconfig"

# tmux
set -x TERM "xterm-256color"
alias t="tmux"
alias tmx="tmux"

# vim
alias v="vim"
alias vo="vim -O"
alias vd="vimdiff"

# Vagrant
alias va="vagrant"
alias vai="vagrant init"
alias vau="vagrant up"
alias vah="vagrant halt"

alias nosetests="python3 -m nose"

alias python='python3'
alias py=python
alias pip='pip3'
