#!/usr/bin/env fish

abbr b 'build'
abbr bp 'build -p'
abbr bd 'build -d -b build-debug'
abbr bdp 'build -d -b build-debug -p'

# git
abbr g "git"
alias gi "git init && git aa && git ci"

# mkdir
abbr md "mkdir"

# ls
# TODO: pls, check lsd, pls
alias ls "exa"

abbr l "ls"
alias la  "ls -A"
alias lA  "ls -a"
alias ll  "ls -lhA"
alias lsa "ls -A"
alias lsA "ls -a"

# open script
abbr o "open"
abbr oc "vim $HOME/.config/fish/config.fish"
abbr og "vim $HOME/.gitconfig"

# tmux
set -x TERM "xterm-256color"
alias t "tmux"
alias tmx "tmux"

abbr t "tmux"
abbr ta "tmux a"
abbr tl "tmux ls"

# vim
abbr v "vim"
abbr vo "vim -O"
abbr vd "vimdiff"

# Vagrant
abbr va "vagrant"
abbr vai "vagrant init"
abbr vau "vagrant up"
abbr vah "vagrant halt"

alias nosetests "python3 -m nose"

alias python 'python3'
alias py python
alias pip 'pip3'

alias today "date +%Y-%m-%d"
