#!/usr/bin/env fish

# ls

#which lsd &>/dev/null
#if test $status -eq 0 ]; then
#	alias ls=lsd
#else
#	ls -GFh &>/dev/null &&
#		alias ls='ls -GFh'
#
#	ls --color=tty &>/dev/null &&
#		alias ls='ls --color=tty'
#fi

alias ls="lsd"
alias l="ls"
alias la="ls -A"
alias lA="ls -a"
alias ll="ls -lhA"
alias lsa="ls -A"
alias lsA="ls -a"

# git
alias g="git"

# open script
alias o="open"

# tmux
set -x TERM "xterm-256color"

# vim
alias v="vim"
alias vo="vim -O"
alias vd="vimdiff"

# Vagrant
alias va="vagrant"
alias vai="vagrant init"
alias vau="vagrant up"
alias vah="vagrant halt"

alias nosetests="python3 -m nose"

alias python='python3'
alias py=python
alias pip='pip3'
