#!/bin/bash

# Set ls to colored output
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad
ls -GFh 1>/dev/null 2>/dev/null && alias ls='ls -GFh'
ls --color=tty 1>/dev/null 2>/dev/null && alias ls='ls --color=tty'

alias tmux="TERM=xterm-256color tmux"
alias ll="ls -lha"
alias sl="ls"
alias ..="cd .."

alias g="git"
alias o="open"
alias v="vim"
