#!/usr/bin/bash

DEFAULT='\[\033[m\]'
RED='\[\033[0;31m\]'
BROWN='\[\033[2;33m\]'
GREEN='\[\033[2;32m\]'
BLUE='\[\033[1;34m\]'
GREEN2='\001\033[0;32m\002'
YELLOW='\001\033[0;33m\002'
LGREEN='\[\033[0;32m\]'

GBWN='\001\033[1;33m\002'
GRED='\001\033[1;31m\002'
DEFA='\001\033[m\002'

function get_deleted()
{
	printf "%s" "`git shd 2>/dev/null | head -n1 | sed -E "s/^(.+)$/-/"`"
}

function get_modified()
{
	printf "%s" "`git shm 2>/dev/null | head -n1 | sed -E "s/^(.+)$/*/"`"
}

function get_new()
{
	del="$(get_deleted)"
	mod="$(get_modified)"

	GN=`git shn 2>/dev/null | head -n1`
	test -z "$GN" && test -z "${del}"  && test -z "${mod}" && printf "${GREEN2}" && return
	printf ${YELLOW}
}

function git_status()
{
	test -z "${del}" && test -z "${mod}" && printf "" && return

	printf " ${DEFA}(${GRED}${del}${GBWN}${mod}${DEFA})"
}

function get_branch()
{
	del="$(get_deleted)"
	mod="$(get_modified)"

	printf "%s%s" "`git branch 2>/dev/null | grep '^*' | colrm 1 2 | sed -E "s/^(.+)$/ \1/"`" "$(git_status)"
}

function get_status()
{
	ST=$?
	test ${ST} -eq 0 && printf "" && return

	printf "${GRED}${ST} "
}

function default_ps1()
{
	STATUS="\$(get_status)"
	USER="${RED}\u${BROWN}@${GREEN}\h${DEFAULT}"
	PROMPT="${LGREEN}\$${DEFAULT} "
	BRANCH="\$(get_new)\$(get_branch)${DEFAULT}"
	LOC="${BLUE}\w${DEFAULT}${BRANCH}"

	export PS1="${STATUS}${USER} [${LOC}]${PROMPT}"
}
