#!/bin/bash

test -z ${1} && echo "Provide path to the file" >&2 && exit 1

EXTENSION=`echo ${1} | sed -E 's/[^/]*\.([^/]*)$/\1/'`

if [ $EXTENSION == "zip" ]; then
	unzip ${1}
elif [ $EXTENSION == "tar.gz" ]; then
	tar -xzf ${1}
elif [ $EXTENSION == "tar" ]; then
	tar -xf ${1}
elif [ $EXTENSION  == ".gz" ]; then	
	gunzip ${1}
fi
