#!/bin/bash

# TODO:
#  - Refactor design and implementation
#  - provide fuzzy serach
#  - when i specify path that end with file and file does not exist cd to dir and fzf -1 there file

EDITOR=nvim

if [ -z ${1} ]; then
	FILES="`fzf -1 -m --height=5%`"
	test -z "${FILES}" && exit 0

	${EDITOR} -O ${FILES}
	exit 0
fi

ECHO_OUT=""
test ! -z ${2} && ECHO_OUT=true

test -f "$(realpath ${1})" && ${EDITOR} "${1}" && exit 0
test -d "$(realpath ${1})" && cd "$(realpath ${1})" && (
	FILES="`fzf -1 -m --height=5%`"
	test -z "${FILES}" && exit 0

	${EDITOR} -O ${FILES}
	exit 0
) && exit 0

SCRPT=`which ${1} 2>/dev/null`
if [ $? -eq 0 ] ; then
	${EDITOR} ${SCRPT}
	exit 0;
fi

if [ -d src ]; then
	FILE_WHERE="src"
	test -d tests && FILE_WHERE="src tests"
elif [ -d tests ]; then
	FILE_WHERE="tests"
else
	FILE_WHERE="."
fi

HEADER_WHERE="."
test -d include && HEADER_WHERE="include"

EXTENSION=`echo ${1} | sed -E 's/[^/]*\.([^/]*)$/\1/'`

if [ "$EXTENSION" == "${1}" ]; then
	FILE=`find $FILE_WHERE -type f | grep "${1}\.cpp$" | head -n 1`
	HEADER=`find $HEADER_WHERE -type f | grep "${1}\.h$" | head -n 1`

	if [ -z ${FILE} ]; then
		if [ -z ${HEADER} ]; then
			FILES="`fzf -1 -m --height=5% -q ${1}`"
			test -z "${FILES}" && exit 0
			${EDITOR} -O ${FILES}
			exit 0
		fi

		test -z ${ECHO_OUT} && ${EDITOR} ${HEADER} && exit 0
		echo "HEADER=${HEADER}"
	else
		if [ -z ${HEADER} ]; then
			test -z ${ECHO_OUT} && ${EDITOR} ${FILE} && exit 0
			echo "FILE=${FILE}"

		else
			test -z ${ECHO_OUT} && ${EDITOR} -O ${HEADER} ${FILE} && exit 0
			echo "HEADER=${HEADER}; FILE=${FILE}"
		fi
	fi
else
	FILE=`find $FILE_WHERE -type f | grep "${1}$" | head -n 1`
	test -z ${FILE} && echo "open: Unable to open file ${1}" && exit 1
	test -z ${ECHO_OUT} && ${EDITOR} ${FILE} && exit 0
	echo "FILE=${FILE}"
fi

exit 0
